apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: guestbook-monitor
  labels:
    app: guestbook
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [message-service,ui,guestbook-service]}
  podMetricsEndpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s