spring:
  application:
    name: ui
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: "1.0"
    baggage:
      remote-fields: x-request-id,x-ot-span-context
  session:
    store-type: redis
  redis:
    host: ${REDIS_HOST}
    port: 6379
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"